language: node_js

node_js:
- 4.2.2

sudo: false

env:
  global:
  - secure: "ZJEa+rGTBPqQVmMBFls6zVi2k8LRGtz9NnujHMb41ScQEMpIHAWj4X6BEu2LtssZbImfaUTVFY2uR2AKbEajETiJD6K+gc1EkjAgp8yhdpCJ+rDGGIGCgy2zDmuBQ1WTgbugH12pm0p7/1LgdvLZIvzZvGHl7UBujIK1jcHGtw0d/NGShF9JzDw1ztOfce/REFAvG5FduNsAU9vUQ6CUSJf2a40uyZYdcLRhTudZmpFsO2Ol4d0thftG53GXMghL6xRSl/0i5ZRBuGIHQ/yr18bvytai0MpX2gkM5jbsdgo1PoPj75uDRGBlOz0b0VMXuNuF1rfYi38CaeI9F0PH/Um/JX2oIcjrXiXe/TZzJWFVkuMMZWyRluKtERqCjDDTJUqkbJ8KcWsLlAw8ANnLA02MNZNHdjB9ir83eMCEDUbiBDDbeyo9bYErVN90pnBIH0r2r5Xc4n9FabjSrpFRadsbkqO/JCYoUN/f9xmOiQdmV0i41hrVAkihGAMG7ny2J/7XgVI1a1xs146HxqzffwAq0I7z4dQzkt7kbKuuVf7SoCeTiJQkrvTObOG5L0qpzAaJ8dIAf5zkSp+0f8peOW8wIo2srkwBHlboxFSQJPuJ5WbNhtNazOX0gUYbqGw1jd5OXiyZxObgCjt5jMr8buOoT4/vzIfuC6K4YYROF9c="
  - secure: "hR7PDae72ejwCEF/rHMsem/4tetvjUHu/ZoHatmnXnprwHrqjNUSfbTzrCx9i4zl4QEh5ICjO2MEPh/S15MU0PVu/Djjgh1KAHip+RlCyS4v923dHNpQgah60UgGLzl+AujpXKfS5ZhaZYfUamwkf9ABtqWNQyhRVz/eBxD4d50sQo9Irg/rUHIx7ES1MD8z+EBIP1QneM4jg+f+/xLh4UMwPa5m2njQx0tu4B8/NpBW+eJcXXs62crPfY53MHDG25sYIH19rUY4InS3VgmZl6WTrmrROvs0AURr/Nq063rXoq/eNhFGoQFwyx3UAVtJNuYbNFSGd76lHyJ23lS3RBvjK4ouaDL+BWcGwTh89BT8O8Ad+HuS6DoB/9sGnqaHuF4+keBZy4Pf4H66oJjA8VFjt6T7jUdtmsLP9lREJfY6Pm3wuvXG4MBFZv3It82TWSu+QHWQQbdxkGuj68IILpCu+4aCSad4wM7slwAtF3YsWVD+SQBCgcKkhxLVtJ+xfVlLj71SPTDnOnu57rBNd0gkht1kVCyLlmaFtKFYyyptruftAWE0IhbnGtosFLKx5DczibTqayGwiFPbGOVO/KPqipH16u+IT5QkgCU2CHkM4ySVJLxSZhklgSNsADTC/x6LmuJuk7zFjzM50q25HMsKJS+FL/YhuPEkMvweMuY="

addons:
  sauce_connect: true

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- gulp !test/prepare
- gulp !test.unit/run
- gulp !test.e2e/run
