language: node_js

node_js:
- 4.2.2

sudo: false

env:
  global:
  - secure: "KVuewFdYnNu2va7a3C9XFN5dH78I19bFehALSo/OW28h3cYtOxbtNQbYASSQyuFgP7iV/AIAO+CFJKKBH7fL3Juq8veESdQczHkYe3E4MlNsrZNCwNV0LpYXzrogEipK3eOyHIn/BgRfZi0qD32YEtFFo7swnzNTfk+5XpDEG9Tpt820NmkgabV8Mk1LB9o632OtOH5ZfTys29hrwgnxTDNMRFyPZ8fthDAx2zM43ycx0w3MbBwR97YlVGjoP2EAb8iQhTBBpS5jBvcqVAbyvkWIjWSOqaqui6xZ9XRbG8DkbqUJmEgE/8HjXZ2NdmugAq6kfGOWcD9tUtS1xGmS23aD/uH+5rrI9xYVWtESatShC7dilr+reys1mgtMMATbdRhp5VyOKrY9gKCbcuGkQi8ejpOZMLO4LMj5Yd4XYv0KcA2QWOjlxIg3cWmYTjfTtbQUtImJUe6e+bSbiJWMT4jHuB61Qn7+owhAhbbqlgswuVF45wqvA5BVQnruC88QJQZaZhA5oCubzc8GwTd1B05WF9w14QG3eg7+A+U9qY5/aNxnLc4pT/F/x44CtscFRu+mL4Ta03hB2hzcetVK2DS70fSqkw/0PMFBtgV4ZnOUgtuCMCvST4QCXFKhs+eOs/QwlHvWCU4yIaoWADsD+e01MfFJ5Ih1lp3LNduhUlg="
  - secure: "O/o7D3kbJEQqM4m80pzlPVdkdgRVDSDaoyA+f1IQPiKdD6vadHNq0q62wEj97iQOEaIigGfRKIxLiqBWnX6rS6Dp3vRhu3AvVTs1fuNqPjxMgqKfZ3ulaSC69HKrcNLFI1CDrMBvtYkzLdeV1sxEwu1miaPuUOn0VsyXIjUmtwFK2dK6IpsmoK4XSUwLFCogfHVO7ocXw5oN2DXMvmQ+ZfsTkAw1tAn+srFPdFM9iWrC+dMWzHFmW8g6MPjsjV4RoAwf0yfwVnXiEHi3gTIx3zxdTFGelnJfykaHL7x1dGSjf2Lkm3LIgoP8SyUP7rd7gxunt5pBVaMW7huYypQi1Ls2yuBrJVcxq4qySctEN0Y2W/v7qfaJ+cOuffeC6KsTOfiY9R7y+Wdb+JTcm0IedU42mGBB2YVsU5grV64f1CrlxnFx2O3QMTSGdWxq/bwK50pUNeg9KAc0B25vF78U0toOzpRsq1gq0bgB4IVzjGWPaFD9nxgsEF1eP1W0oZ1TAZM9/rsj73XagpsHq2mdB1girihDUdz2Wpyp5pHE6QyuUSmyTxnn+jedh8qin93jDsSFl9lglULdnIhrQcpjfgjDOYeHAe10TrzQneylSvcHUjgwF0AS3wbrJBRxa6wfybmoYKUq/cglW9o5I1CbtQU6gteeMr2IYbR/R3nauqU="

addons:
  sauce_connect: true

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- gulp !test/prepare
- gulp !test.unit/run
- gulp !test.e2e/run
