language: node_js

node_js:
- 4.2.2

sudo: false

env:
  global:
  - secure: KigJ+AXnpNArnpdwTCmnYPiyk8i/URg35Hn96D8iWH5/fLduCSUgjex4oFolqwoJloz2K2+HpODYr79Kzvt8atrFS1BVdxK4GSZs/der+Unga1CEL9+HgFEpbOQRqinAEXn4676Go0Bla76X7klOypYTzKccxGFHbS0lZF3Lex4yxIpMfMGjuXCrUmEY7NAbVkTEdBhb/FmPOq/0Gp+tVv7vPX+T5qEWlCaIhdUwzb5pGK/HUDVPfntQbtkk8gDvj91mgtJudS5QpGh46q4PDoaRp5XiuQW9Ax996ymfruSdZ/q5WND6dV7gs/Ic3zOROenPwk1s4ukiq+ByGBAhO1m9q3aNsSb9N9owtnVQIIIGzZ5LgeIJgowTvA7cGz8lGWMPH+0XK+8seu68SmY27BI77ouEOdnTTv/HTiqfMQw4HqOeXE7StgFXf4xcU0YyXzzc60fljxjz54nEH7/ToZoeqfJTDGE1HxpkYq2hXIjxORqOSPiswHnkIYaIwXKUgflAGdKx48gX46+O+i5gcP+HrfuHMWrNG6CbFQLdUngFP2dazyZECf7t4nuPERFGfYT2pWRL+xDJfbsWiNzMsMGq4rGlUTXmVy8qnQi5gYNMhL46EHvWLS2xh9zG9aqZnYBSSWAaMeg4EBUg+m5szQ1fUawOrl41y7O9Ai8qqos=
  - secure: TZ1JmkG3of4+YexsuFnWxE3fvbijSKkX3MtCi7ZTy+ePje/oOaw2amEUU6L5yqaCMEZoWK9JROZ1J1BUFi9xNbjujMFNoF3frqxLz4XY2RPOgwZtg/6OXbzIZ7Nz/o8Xgj0swNXJJvU6lcu+MuhoMPfsM//x9HWVEpi8TMpQBjjzbaCWyQ4gRT8ck1JVn+0iPfgx10ozX32dij6CSN5o6pTwdDFtMQ1VgJ7+lgbRSDU2jzgY2fIvgI6/6AI+IQ8iZrfQWvLrwSFG8qgx0qr8baLbbZ1GMzdj+5FuEoT0rZ4AW7VoKzIw1/7FQWOAx2FAZ+Z+iCqWsHfK/0pXPkAu6B3u7KOQaOr7Vv7kI0hH9JDA2vrDR00juiEo142jkp8BFuUDDoA4O4NkJhjfxKon1zZSiuQMGkeFCsBIdpoW0jWdp9AS+giggOubaHgM+gcEzrwzhzArWZxc2SmOzhUsskZOlDGRTS9st/uJihgFdiVuWoBr6aaKpjLoNpDcbtAG4nC0sKwMweChBcoEdn6xNFFtCWdSnBtmCpd0flFy0itjpyoCCeNmjGVlG/P0ppAxLTezgRoMgTy6sUGzhELa1agc5hC11s15a0NBv9uK7GQdzGHgoAgMYERYt2icrh/jJ033rUTi1ks4duPbVLtzLzyVo2pNrOy0lV2aSdeYSqM=

addons:
  sauce_connect: true

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- gulp !test/prepare
- gulp !test.unit/run
- gulp !test.e2e/run
